rtl/cpu_pkg.sv
rtl/ALU.sv
rtl/Branch_Predictor.sv
rtl/Comparator.sv
rtl/Decoder.sv
rtl/EX_Operand_Parser.sv
rtl/EX_Result_Parser.sv
rtl/EX_Stage.sv
rtl/Forward_Mux.sv
rtl/ID_EX_Reg.sv
rtl/ID_Stage.sv
rtl/IF_ID_Reg.sv
rtl/IF_Stage.sv
rtl/Imm_Parser.sv
rtl/Instr_Mem.sv
rtl/PC_Fetch.sv
rtl/Register_File.sv
rtl/Stall_Controller.sv
rtl/Flush_Control.sv
rtl/MEM_Control.sv
rtl/EX_MEM_Reg.sv
rtl/Memory.sv
rtl/MEM_Stage.sv
rtl/MEM_WB_Reg.sv
rtl/WB_Control.sv
rtl/Core.sv
testbenches/ALU_tb.sv
testbenches/Branch_Predictor_tb.sv
testbenches/Decoder_tb.sv
testbenches/ID_Stage_tb.sv
testbenches/IF_Stage_tb.sv
testbenches/Imm_Parser_tb.sv
testbenches/Instr_Mem_tb.sv
testbenches/PC_Fetch_tb.sv
testbenches/Register_File_tb.sv
testbenches/EX_Stage_tb.sv
testbenches/MEM_Stage_tb.sv